# Generated by Django 3.2.2 on 2023-03-14 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_oauth2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OauthClientUuid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_oauth2.oauthclient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
