# Generated by Django 3.2.2 on 2023-03-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_oauth2', '0003_oauth2token'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauth2token',
            name='is_alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='oauth2token',
            name='client_id',
            field=models.CharField(db_index=True, max_length=48, null=True),
        ),
    ]
