# Generated by Django 3.2.2 on 2023-03-14 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_oauth2', '0006_authorizationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorizationcode',
            name='expires_in',
        ),
        migrations.RemoveField(
            model_name='authorizationcode',
            name='is_alive',
        ),
        migrations.RemoveField(
            model_name='authorizationcode',
            name='issued_at',
        ),
    ]
